"""Auth module

Revision ID: 87424e5b4208
Revises: 8b285ea918d6
Create Date: 2022-06-06 13:37:20.598023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87424e5b4208'
down_revision = '8b285ea918d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.String(length=150), nullable=False),
    sa.Column('auth_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_hash')
    op.drop_table('users_history')
    # ### end Alembic commands ###
